name: ci

on:
  workflow_dispatch:
  push:
    paths:
      - "playlist.txt"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install yt-dlp
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade --pre "yt-dlp[default]"

      - name: Download videos
        run: |
          yt-dlp \
            --verbose \
            --sleep-requests 3 \
            --sleep-interval 5 \
            --max-sleep-interval 15 \
            --retries 10 \
            --fragment-retries 10 \
            --ignore-errors \
            --batch-file playlist.txt
